CREATE TABLE "backup_audit_log" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"action" text NOT NULL,
	"resource_type" text NOT NULL,
	"resource_id" varchar NOT NULL,
	"user_id" varchar NOT NULL,
	"ip_address" text NOT NULL,
	"user_agent" text,
	"details" jsonb,
	"success" boolean DEFAULT true NOT NULL,
	"error_message" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "backup_configurations" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"type" text NOT NULL,
	"schedule_type" text NOT NULL,
	"schedule_time" text,
	"schedule_day" integer,
	"schedule_date" integer,
	"schedule" text,
	"enabled" boolean DEFAULT true NOT NULL,
	"retention_days" integer NOT NULL,
	"storage_provider" text NOT NULL,
	"storage_path" text,
	"storage_credentials" jsonb,
	"encryption_enabled" boolean DEFAULT true NOT NULL,
	"encryption_key" text,
	"compression_enabled" boolean DEFAULT true NOT NULL,
	"compression_algorithm" text DEFAULT 'gzip' NOT NULL,
	"verification_enabled" boolean DEFAULT true NOT NULL,
	"notification_enabled" boolean DEFAULT true NOT NULL,
	"notification_email" text,
	"max_parallel_jobs" integer DEFAULT 1 NOT NULL,
	"timeout_minutes" integer DEFAULT 60 NOT NULL,
	"last_run_at" timestamp,
	"next_run_at" timestamp,
	"total_runs" integer DEFAULT 0 NOT NULL,
	"successful_runs" integer DEFAULT 0 NOT NULL,
	"failed_runs" integer DEFAULT 0 NOT NULL,
	"average_duration_seconds" integer,
	"last_backup_size" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "backup_jobs" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"configuration_id" varchar NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"type" text NOT NULL,
	"priority" integer DEFAULT 5 NOT NULL,
	"started_at" timestamp,
	"completed_at" timestamp,
	"duration_seconds" integer,
	"backup_size_bytes" integer,
	"backup_path" text,
	"checksum" text,
	"compression_ratio" real,
	"file_count" integer,
	"error_message" text,
	"metadata" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "restore_points" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"backup_job_id" varchar NOT NULL,
	"snapshot_type" text NOT NULL,
	"verification_status" text DEFAULT 'pending' NOT NULL,
	"verification_date" timestamp,
	"total_size_bytes" integer,
	"is_archived" boolean DEFAULT false NOT NULL,
	"expires_at" timestamp,
	"tags" text[],
	"metadata" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL
);
